name: Publish Prod All Packages

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      max-parallel: 1
      matrix:
        package: [core, crypto, entity, image, qr, services, schema, web, cli-core, crypto-cli]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Remove Mono-Repo Node Modules
        run: |
          rm package.json
          rm package-lock.json

      - name: Check package version does not contains -next
        run: |
          cd packages/${{ matrix.package }}
          PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')
          echo Package Version $PACKAGE_VERSION
          if [[ $PACKAGE_VERSION == *"-next"* ]]; then
            echo "Error: package version contains -next"
            exit 1
          fi

      - name: Run Dist
        run: |
          cd packages/${{ matrix.package }}
          npm install
          npm run dist

      - name: Cleanup package properties
        run: |
          cd packages/${{ matrix.package }}
          npm pkg delete scripts
          npm pkg delete devDependencies

      - name: Publish
        run: |
          cd packages/${{ matrix.package }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
